project_id = "cbeenkpjpnhmtqtnjiyd"

[functions.send-notification]
verify_jwt = false

[functions.mark-action-done]
verify_jwt = false

[functions.xero-callback]
verify_jwt = false

[functions.google-calendar-callback]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.iwi-pull-snapshot]
verify_jwt = false
