-- Real, small, content-only addition to the existing "Drought / Water
-- Shortage" hazard entry (seeded 20260904030000_drought_water_shortage_hazard.sql).
-- Raised from a Facebook-post fact-check, 15 Sept 2026: the post's claims
-- around water storage, conservation, backup supply and having a clear
-- plan all checked out against real, live content -- but "rainwater
-- collection" specifically was thin, mentioned only as a supply type, not
-- covered as its own readiness practice. This adds one sentence to each
-- field covering collection systems, first-flush diverters, and
-- roof/gutter maintenance for water quality -- no new hazard type, no
-- workflow_steps change, content only.
--
-- likely_impact/what_to_do are trustee-editable free text
-- (EmergencyPlanManager.js). Matched on the exact current seeded text, on
-- both fields, so this is a safe no-op anywhere a trustee has already
-- edited either -- same guard used in
-- 20260904050000_water_tank_item_drought_note.sql. Confirmed via direct
-- query before writing this: the seeded text is still unedited on Opeke.

update public.emergency_plan_hazards
set
  likely_impact = 'Drought and prolonged dry weather can leave a marae''s water supply critically low or fully restricted, whether the supply is a tank, a bore, or a council connection subject to restrictions. Earth Sciences New Zealand (NIWA) declared a "Very Strong" El Nino on 2 July 2026, with peak effects expected over spring and summer 2026/27 and the greatest risk of below-normal rainfall over the northern and eastern North Island and the eastern South Island. Risk is highest during large gatherings (tangihanga, hui, wananga), when water demand is at its peak and a shortage affects the most people at once, and for marae relying on a rainwater tank or a single bore with no backup source. A collection system with dirty gutters, blocked downpipes, or no first-flush diversion can leave water unsafe to use even while the tank itself is still full -- a maintenance problem becoming a supply problem at the worst possible time.',
  what_to_do = 'Before: know your real tank capacity and how many days of normal use it represents, and keep the Civil Defence-recommended emergency minimum -- at least 3 litres of drinking water per person per day, for 3 or more days -- genuinely separate from everyday use, not counted as part of it. If your supply includes roof-collected rainwater, maintain the collection system itself, not just the tank: clear leaves and debris from gutters and downpipes regularly, and fit or check a first-flush diverter so the dirtiest initial run-off from each rain event is diverted away from the tank instead of into it. If you rely on a trucked water carrier, confirm now that the provider is on Taumata Arowai''s real Public Register of Drinking Water Supplies (Hinekorako), before you actually need to book one. Monitor your regional council and the real NZ Drought Index (NIWA/MPI) for your district as spring and summer approach. During: follow every restriction your water supplier or council issues exactly as instructed, and ration non-essential use (gardens, washing vehicles, topping up pools) immediately once dry conditions are forecast, before restrictions become mandatory. If your regular supply fails and only untreated rainwater, bore or stream water remains, do not use it for drinking, cooking or brushing teeth unless it has been boiled -- it is fine for laundry, cleaning or toilet flushing. After: restock your emergency reserve, log what happened and any real costs, and contact your local Rural Support Trust if this was part of a wider declared drought event.'
where hazard_type = 'Drought / Water Shortage'
  and entity_id is null
  and likely_impact = 'Drought and prolonged dry weather can leave a marae''s water supply critically low or fully restricted, whether the supply is a tank, a bore, or a council connection subject to restrictions. Earth Sciences New Zealand (NIWA) declared a "Very Strong" El Nino on 2 July 2026, with peak effects expected over spring and summer 2026/27 and the greatest risk of below-normal rainfall over the northern and eastern North Island and the eastern South Island. Risk is highest during large gatherings (tangihanga, hui, wananga), when water demand is at its peak and a shortage affects the most people at once, and for marae relying on a rainwater tank or a single bore with no backup source.'
  and what_to_do = 'Before: know your real tank capacity and how many days of normal use it represents, and keep the Civil Defence-recommended emergency minimum -- at least 3 litres of drinking water per person per day, for 3 or more days -- genuinely separate from everyday use, not counted as part of it. If you rely on a trucked water carrier, confirm now that the provider is on Taumata Arowai''s real Public Register of Drinking Water Supplies (Hinekorako), before you actually need to book one. Monitor your regional council and the real NZ Drought Index (NIWA/MPI) for your district as spring and summer approach. During: follow every restriction your water supplier or council issues exactly as instructed, and ration non-essential use (gardens, washing vehicles, topping up pools) immediately once dry conditions are forecast, before restrictions become mandatory. If your regular supply fails and only untreated rainwater, bore or stream water remains, do not use it for drinking, cooking or brushing teeth unless it has been boiled -- it is fine for laundry, cleaning or toilet flushing. After: restock your emergency reserve, log what happened and any real costs, and contact your local Rural Support Trust if this was part of a wider declared drought event.';
